version: '3'

services:
   frontend:
     image: kgunarno/bliblimart-frontend:6
     ports:
       - "80:80"
     deploy:
       placement:
         constraints: [node.role == worker]
     environment:
      - API_URL=backend:8082
     logging:
       driver: "fluentd"
       options:
         fluentd-async-connect: "true"
         fluentd-address: future_fluentd:24224
         tag: frontend
         
   backend:
     image: kgunarno/bliblimart-backend:11
     ports:
       - "8082:8080"
     restart: always
     deploy:
       placement:
         constraints: [node.role == worker]
     logging:
       driver: "fluentd"
       options:
         fluentd-async-connect: "true"
         fluentd-address: future_fluentd:24224
         tag: backend
     
