version: '3'

services:
   frontend:
     image: kgunarno/bliblimart-frontend:8
     ports:
       - "80:80"
     deploy:
       placement:
         constraints: [node.role == worker]
     environment:
      - API_URL=future_backend:8082
     logging:
       driver: "fluentd"
       options:
         fluentd-async-connect: "true"
         fluentd-address: fluentd:24224
         tag: frontend
         
   backend:
     image: kgunarno/bliblimart-backend:18
     ports:
       - "8082:8080"
     restart: always
     deploy:
       placement:
         constraints: [node.role == worker]
     logging:
       driver: "fluentd"
       options:
         fluentd-async-connect: "true"
         fluentd-address: 0.0.0.0:24224
         tag: backend
         
   redis:
     image: redis
     ports:
       - "6379:6379"
     restart: always
     deploy:
       placement:
         constraints: [node.role == worker]
     logging:
       driver: "fluentd"
       options:
         fluentd-async-connect: "true"
         fluentd-address: future_fluentd:24224
         tag: redis
         
   db:
     image: mongo
     ports:
       - "27017:27017"
     deploy:
       placement:
         constraints: [node.role == worker]
     logging:
       driver: "fluentd"
       options:
         fluentd-async-connect: "true"
         fluentd-address: 172.31.54.208:24224
         tag: db
     
