version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    deploy:
      placement:
        constraints: [node.role == manager]

  kibana:
    image: kibana:7.8.1
    ports:
      - "5601:5601"
    deploy:
      placement:
        constraints: [node.role == manager]

