version: '3'

services:         
   backend:
     image: kgunarno/bliblimart-backend
     ports:
       - "8082:8080"
     restart: always
     deploy:
       placement:
         constraints: [node.role == worker]
     logging:
       driver: "fluentd"
       options:
         fluentd-async-connect: "true"
         fluentd-address: future_fluentd:24224
         tag: wordpress
