version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      - "cluster.name=future"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    deploy:
      placement:
        constraints: [node.role == manager]
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        fluentd-address: future_fluentd:24224
        tag: elasticsearch    

  kibana:
    image: kibana:7.8.1
    ports:
      - "5601:5601"
    deploy:
      placement:
        constraints: [node.role == manager]
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        fluentd-address: future_fluentd:24224
        tag: kibana
        
  fluentd:
    image: kgunarno/futurefluentd:1.0
    volumes:
      -   "./fluentd/conf:/fluentd/etc"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      
  apm:
    command: --strict.perms=false
    image: docker.elastic.co/apm/apm-server:7.8.1
    ports:
      - 8200:8200
    volumes:
      - "./apm/apm-server.yml:/usr/share/apm-server/apm-server.yml"
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        fluentd-address: future_fluentd:24224
        tag: apm


