version: '3'
services:
  nginx:
    image: nginx:latest
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
        - "80:80"
    volumes:
        - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
