version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    user: root
    volumes:
      - "prometheus:/etc/prometheus:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - cadvisor
    deploy:
      placement:
        constraints: [node.hostname == 172.31.54.208]

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    ports:
      - 9000:8080
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      labels:
        prometheus-job: "cadvisor"
volumes:
  prometheus:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: "ec2-user@172.31.54.208:/volumes/prometheus"
      IdentityFile: "/root/.ssh/id_rsa"
      allow_other: ""
