version: '3'
services:
  swarmpit:
    image: "swarmpit/install:1.9"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
    - INTERACTIVE=0
    - STACK_NAME=future
    ports:
    - "888:888"
    deploy:
      placement:
        constraints: [node.role == manager]
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        fluentd-address: future_fluentd:24224
        tag: swarmpit