version: '3'

services:
   frontend:
     image: kgunarno/bliblimart-frontend:23
     ports:
       - "80"
     deploy:
       placement:
         constraints: [node.role == worker]
     logging:
       driver: "fluentd"
       options:
         fluentd-async-connect: "true"
         fluentd-address: 0.0.0.0:24224
         tag: frontend
         
   backend:
     image: kgunarno/bliblimart-backend:20
     ports:
       - "8080"
     restart: always
     deploy:
       placement:
         constraints: [node.role == worker]
     logging:
       driver: "fluentd"
       options:
         fluentd-async-connect: "true"
         fluentd-address: 0.0.0.0:24224
         tag: backend
         
   redis:
     image: redis
     ports:
       - "6379"
     restart: always
     deploy:
       placement:
         constraints: [node.role == worker]
     logging:
       driver: "fluentd"
       options:
         fluentd-async-connect: "true"
         fluentd-address: 0.0.0.0:24224
         tag: redis
         
   db:
     image: mongo
     ports:
       - "27017"
     deploy:
       placement:
         constraints: [node.role == worker]
     logging:
       driver: "fluentd"
       options:
         fluentd-async-connect: "true"
         fluentd-address: 0.0.0.0:24224
         tag: db
     
